server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: auth_user
    password: auth_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
  main:
    allow-bean-definition-overriding: true

jwt:
  issuer: "http://localhost:9000"
  audience: "tokopaedi-api"
  access-ttl: "PT15M"      # 15 menit
  refresh-ttl: "PT30D"     # 30 hari
  key:
    size: 2048

iam:
  base-url: "http://localhost:9100"
  service-token: "dev-service-token"
  http:
    response-timeout-ms: 800

resilience4j:
  circuitbreaker:
    instances:
      iam:
        registerHealthIndicator: true
        slidingWindowSize: 20
        permittedNumberOfCallsInHalfOpenState: 2
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      iam:
        maxAttempts: 2
        waitDuration: 200ms
  timelimiter:
    instances:
      iam:
        timeoutDuration: 1s

webclient:
  connect-timeout-ms: 300
  read-timeout-ms: 800
