server:
  port: 9000
  servlet:
    context-path: /

app:
  errors:
    verbose: true

spring:
  application:
    name: auth-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: auth_user
    password: auth_pass
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: true
  main:
    allow-bean-definition-overriding: true
  web:
    resources:
      add-mappings: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service/.well-known/jwks.json

jwt:
  issuer: "http://localhost:9000"
  audience: "tokopaedi-api"
  access-ttl: "PT15M"      # 15 menit
  refresh-ttl: "P30D"      # 30 hari

auth:
  registration:
    account-registered:
      topic: ${AUTH_REGISTRATION_ACCOUNT_REGISTERED_TOPIC:account-registered}
      max-attempts: ${AUTH_REGISTRATION_ACCOUNT_REGISTERED_MAX_ATTEMPTS:3}
      backoff-ms: ${AUTH_REGISTRATION_ACCOUNT_REGISTERED_BACKOFF_MS:500}

iam:
  enabled: true
  service-token: dev-service-token
  http:
    response-timeout-ms: 800

webclient:
  connect-timeout-ms: 300
  read-timeout-ms: 800

resilience4j:
  circuitbreaker:
    instances:
      iam:
        registerHealthIndicator: true
        slidingWindowSize: 20
        permittedNumberOfCallsInHalfOpenState: 2
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      iam:
        maxAttempts: 2
        waitDuration: 200ms
  timelimiter:
    instances:
      iam:
        timeoutDuration: 1s

#Logging Ganti Off ke "debug"
logging:
  level:
    reactor.netty.http.client: debug
    org.springframework.web.reactive.function.client: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5         # default 30
    initial-instance-info-replication-interval-seconds: 5  # default 40
  instance:
    lease-renewal-interval-in-seconds: 5       # default 30
    lease-expiration-duration-in-seconds: 10   # default 90
