server:
  port: 9200

app:
  errors:
    verbose: true  # dev only; turn off in prod

spring:
  application:
    name: catalog-service
  security:
   oauth2:
     resourceserver:
       jwt:
         jwk-set-uri: http://auth-service/.well-known/jwks.json

  # datasource
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_db
    username: catalog_user
    password: catalog_pass
  jpa:
    hibernate:
      ddl-auto: none # Disable (none) if using fly-away
    properties:
      hibernate:
        jdbc.time_zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
