name: tokopaedi-microservice
services:
  postgres:
    image: postgres:16
    container_name: tokopaedi-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: ["postgres","-c","max_connections=200","-c","shared_buffers=256MB"]
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init/init-multiple-dbs.sql:/docker-entrypoint-initdb.d/00-create-dbs.sql:ro
      - ./init/init-users-and-grants.sql:/docker-entrypoint-initdb.d/01-users-and-grants.sql:ro
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks: [core]

  redis:
    image: redis:7
    container_name: tokopaedi-redis
    command: ["redis-server","--appendonly","yes"]
    ports: ["6379:6379"]
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks: [core]

  kafka:
    image: bitnami/kafka:3.7
    container_name: tokopaedi-kafka
    ports:
      - "9092:9092"     # internal listener (container-to-container)
      - "29092:29092"   # external listener (host-to-container)
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LOG_RETENTION_MS=-1
    networks: [ default ]

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: tokopaedi-kafka-ui
    ports: [ "8082:8080" ]
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on: [ kafka ]
    networks: [ default ]

volumes:
  pgdata:
  redisdata:

networks:
  core:
