name: tokopaedi-microservice
services:
  postgres:
    image: postgres:16
    container_name: tokopaedi-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: ["postgres","-c","max_connections=200","-c","shared_buffers=256MB"]
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init/init-multiple-dbs.sql:/docker-entrypoint-initdb.d/00-create-dbs.sql:ro
      - ./init/init-users-and-grants.sql:/docker-entrypoint-initdb.d/01-users-and-grants.sql:ro
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks: [core]

  redis:
    image: redis:7
    container_name: tokopaedi-redis
    command: ["redis-server","--appendonly","yes"]
    ports: ["6379:6379"]
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks: [core]

volumes:
  pgdata:
  redisdata:

networks:
  core:
