server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      default-filters:
        # Retry hanya untuk GET dan error koneksi/5xx.
        - name: Retry
          args:
            retries: 2                  # total 3 percobaan (1 + 2 retry)
            methods: GET
            series: SERVER_ERROR        # 5xx
            exceptions:
              - java.io.IOException
              - org.springframework.cloud.gateway.support.TimeoutException
            backoff:
              firstBackoff: 200ms
              maxBackoff: 1s
              factor: 2
              basedOnPreviousValue: true

      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1   # /auth/api/v1/... -> /api/v1/...

        - id: iam
          uri: lb://iam-service
          predicates:
            - Path=/iam/**    # /iam/api/v1/... atau /iam/internal/v1/...
          filters:
            - StripPrefix=1   # -> /api/v1/... atau /internal/v1/...

  # Aktivasi discovery-aware http client di Gateway (otomatis by starter)
  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# (Opsional) health/info
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,gateway
