server:
  port: 8080

app:
  errors:
    verbose: true

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 3s
      default-filters:
        # Retry hanya untuk GET dan error koneksi/5xx.
        - name: Retry
          args:
            retries: 2                  # total 3 percobaan (1 + 2 retry)
            methods: GET
            series: SERVER_ERROR        # 5xx
            exceptions:
              - java.io.IOException
              - org.springframework.cloud.gateway.support.TimeoutException
            backoff:
              firstBackoff: 200ms
              maxBackoff: 1s
              factor: 2
              basedOnPreviousValue: true

      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1   # /auth/api/v1/... -> /api/v1/...

        - id: iam
          uri: lb://iam-service
          predicates:
            - Path=/iam/**    # /iam/api/v1/... atau /iam/internal/v1/...
          filters:
            - StripPrefix=1   # -> /api/v1/... atau /internal/v1/...

        - id: catalog
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
          filters:
            - StripPrefix=1

springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    urls:
      - name: auth
        url: /auth/v3/api-docs
      - name: iam
        url: /iam/v3/api-docs
      - name: catalog
        url: /catalog/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5         # default 30
    initial-instance-info-replication-interval-seconds: 5  # default 40
  instance:
    lease-renewal-interval-in-seconds: 5       # default 30
    lease-expiration-duration-in-seconds: 10   # default 90

# health/info
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,gateway
