server:
  port: 8761
  address: 0.0.0.0

spring:
  application:
    name: discovery-service

eureka:
  client:
    # Server tidak perlu register ke dirinya
    register-with-eureka: false
    fetch-registry: false
  server:
    # default saja cukup untuk lab
    wait-time-in-ms-when-sync-empty: 0

management.endpoints.web.exposure.include: health,info
