CREATE DATABASE auth_db WITH ENCODING 'UTF8';
CREATE DATABASE iam_db WITH ENCODING 'UTF8';
CREATE DATABASE profile_db WITH ENCODING 'UTF8';
CREATE DATABASE legacy_db WITH ENCODING 'UTF8';
CREATE DATABASE catalog_db WITH ENCODING 'UTF8';
CREATE DATABASE inventory_db WITH ENCODING 'UTF8';
