server:
  port: 9100
  servlet:
    context-path: /iam

app:
  errors:
    verbose: true

spring:
  application:
    name: iam-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/iam_db}
    username: ${DB_USER:iam_user}
    password: ${DB_PASS:iam_pass}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

internal:
  service-token: dev-service-token

auth:
  jwk-set-uri: http://auth-service/.well-known/jwks.json

management.endpoints.web.exposure.include: health,info

# Nyalakan debug, ganti off ke debug
logging:
  level:
    org.springframework.security: debug
    com.example.iam.security: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5         # default 30
    initial-instance-info-replication-interval-seconds: 5  # default 40
  instance:
    lease-renewal-interval-in-seconds: 5       # default 30
    lease-expiration-duration-in-seconds: 10   # default 90
