server:
  port: 9100
  servlet:
    context-path: /

app:
  errors:
    verbose: true

spring:
  application:
    name: iam-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/iam_db}
    username: ${DB_USER:iam_user}
    password: ${DB_PASS:iam_pass}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: true
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

internal:
  service-token: dev-service-token

auth:
  jwk-set-uri: http://auth-service/.well-known/jwks.json

iam:
  registration:
    default-role: ${IAM_REGISTRATION_DEFAULT_ROLE:CUSTOMER}
    consumer-group: ${IAM_REGISTRATION_CONSUMER_GROUP:iam-service}
    account-registered:
      topic: ${IAM_REGISTRATION_ACCOUNT_REGISTERED_TOPIC:account-registered}

management.endpoints.web.exposure.include: health,info

# Nyalakan debug, ganti off ke debug
logging:
  level:
    org.springframework.security: debug
    com.example.iam.security: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5         # default 30
    initial-instance-info-replication-interval-seconds: 5  # default 40
  instance:
    lease-renewal-interval-in-seconds: 5       # default 30
    lease-expiration-duration-in-seconds: 10   # default 90
