spring:
  application:
    name: iam-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/iam_db}
    username: ${DB_USER:iam_user}
    password: ${DB_PASS:iam_pass}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/.well-known/jwks.json
server:
  port: 9100

internal:
  service-token: dev-service-token

management.endpoints.web.exposure.include: health,info

# Nyalakan debug, ganti off ke DEBUG
logging:
  level:
    org.springframework.security: off
    com.example.iam.security: off
